//
//  PEXLoginStage.h
//  Phonex
//
//  Created by Matej Oravec on 21/09/14.
//  Copyright (c) 2014 Matej Oravec. All rights reserved.
//

#ifndef Phonex_PEXLoginStage_h
#define Phonex_PEXLoginStage_h

typedef enum PEXLoginStage : NSInteger PEXLoginStage;
enum PEXLoginStage : NSInteger {
    PEX_LOGIN_STAGE_1,
    PEX_LOGIN_STAGE_CANCELLING,
    PEX_LOGIN_STAGE_AUTH_KEYGEN,
    PEX_LOGIN_STAGE_AUTH_SOAP,
    PEX_LOGIN_STAGE_PCGT_KEYGEN,
    PEX_LOGIN_STAGE_PCGT_OTT,
    PEX_LOGIN_STAGE_PCGT_SOAP,
    PEX_LOGIN_STAGE_PCGT_VERIFY,
    PEX_LOGIN_STAGE_PCGT_STORE,
    PEX_LOGIN_STAGE_PCLT_FETCH_CL,
    PEX_LOGIN_STAGE_PCLT_PROCESS_CL,
    PEX_LOGIN_STAGE_PCLT_CERT_REFRESH,
    PEX_LOGIN_STAGE_PCLT_CERT_PROCESS,
    PEX_LOGIN_STAGE_PCLT_STORE,
    PEX_LOGIN_STAGE_CHANGEPASS_OTT,
    PEX_LOGIN_STAGE_CHANGEPASS_SOAP,
    PEX_LOGIN_STAGE_CHANGEPASS_KEYGEN,
    PEX_LOGIN_STAGE_CHANGEPASS_REKEY
};

#endif
