//
//  PEXLoginTaskResultDescription.h
//  Phonex
//
//  Created by Matej Oravec on 21/09/14.
//  Copyright (c) 2014 Matej Oravec. All rights reserved.
//

#ifndef Phonex_PEXLoginTaskResult_h
#define Phonex_PEXLoginTaskResult_h

typedef enum PEXLoginTaskResultDescription : NSInteger PEXLoginTaskResultDescription;
enum PEXLoginTaskResultDescription : NSInteger {
    PEX_LOGIN_TASK_RESULT_LOGGED_IN,
    PEX_LOGIN_TASK_RESULT_INCORRECT_CREDENTIALS,
    PEX_LOGIN_TASK_RESULT_ILLEGAL_LOGIN_NAME,
    PEX_LOGIN_TASK_RESULT_NO_NETWORK,
    PEX_LOGIN_TASK_RESULT_CONNECTION_PROBLEM,
    PEX_LOGIN_TASK_RESULT_SERVERSIDE_PROBLEM,
    PEX_LOGIN_TASK_RESULT_CLOCK_PROBLEM,
    PEX_LOGIN_TASK_RESULT_TRIAL_EXPIRED,
    PEX_LOGIN_TASK_RESULT_ACCOUNT_DISABLED,
    PEX_LOGIN_TASK_RESULT_OLD_VERSION,
    PEX_LOGIN_TASK_RESULT_INCOMPATIBLE_VERSION,
    PEX_LOGIN_TASK_RESULT_GENERIC_SERVER_FAIL,
    PEX_LOGIN_TASK_RESULT_UNSPECIFIED_SERVER_FAIL,
    PEX_LOGIN_TASK_RESULT_TLS_CACHE_BUG,
    PEX_LOGIN_TASK_CANCELLED,
    PEX_LOGIN_TASK_DATABASE_ERROR
};

#endif
