//
//  PEXSipCodes.h
//  Phonex
//
//  Created by Matej Oravec on 08/01/15.
//  Copyright (c) 2015 PhoneX. All rights reserved.
//

typedef enum PEXSipCodes
{
    PEX_CALL_CODE_TRYING = 100,
    PEX_CALL_CODE_RINGING = 180,
    PEX_CALL_CODE_CALL_BEING_FORWARDED = 181,
    PEX_CALL_CODE_QUEUED = 182,
    PEX_CALL_CODE_PROGRESS = 183,
    PEX_CALL_CODE_OK = 200,
    PEX_CALL_CODE_ACCEPTED = 202,
    PEX_CALL_CODE_MULTIPLE_CHOICES = 300,
    PEX_CALL_CODE_MOVED_PERMANENTLY = 301,
    PEX_CALL_CODE_MOVED_TEMPORARILY = 302,
    PEX_CALL_CODE_USE_PROXY = 305,
    PEX_CALL_CODE_ALTERNATIVE_SERVICE = 380,
    PEX_CALL_CODE_BAD_REQUEST = 400,
    PEX_CALL_CODE_UNAUTHORIZED = 401,
    PEX_CALL_CODE_PAYMENT_REQUIRED = 402,
    PEX_CALL_CODE_FORBIDDEN = 403,
    PEX_CALL_CODE_NOT_FOUND = 404,
    PEX_CALL_CODE_METHOD_NOT_ALLOWED = 405,
    PEX_CALL_CODE_NOT_ACCEPTABLE = 406,
    PEX_CALL_CODE_REQUEST_TIMEOUT = 408,
    PEX_CALL_CODE_GONE = 410,
    PEX_CALL_CODE_TEMPORARILY_UNAVAILABLE = 480,
    PEX_CALL_CODE_BUSY_HERE = 486,
    PEX_CALL_CODE_REQUEST_TERMINATED = 487,
    PEX_CALL_CODE_INTERVAL_TOO_BRIEF = 423,
    PEX_CALL_CODE_INTERNAL_SERVER_ERROR = 500,
    PEX_CALL_CODE_NOT_IMPLEMENTED = 501,
    PEX_CALL_CODE_SERVICE_UNAVAILABLE = 503,
    PEX_CALL_CODE_DECLINE = 603

} PEXSipCodes;
