//
// Created by Dusan Klinec on 21.07.15.
// Copyright (c) 2015 PhoneX. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface PEXPushRequestPart : NSObject
@property(nonatomic) NSString * action;

/**
* Identifier of the push message request.
* Generated by client.
* Used for duplicates avoidance.
* Client can identify this message in order to cancel its delivery to the target device, used in calls.
*/
@property(nonatomic) NSString * key;

/**
* Expiration time of the message in milliseconds.
* This message should be considered as expired if given amount of time passes from its reception.
* Mainly designed for active push messages such as call requests.
*/
@property(nonatomic) NSNumber * expiration;

/**
* User targeted by this push message request.
*/
@property(nonatomic) NSString * toUser;

/**
* If true this message cancels previous message referenced by key.
*/
@property(nonatomic) BOOL cancel;

+(NSString *) genKey;
-(NSMutableDictionary *) getSerializationBase;

- (instancetype)initWithAction:(NSString *)action toUser:(NSString *)toUser;
+ (instancetype)partWithAction:(NSString *)action toUser:(NSString *)toUser;
- (instancetype)initWithAction:(NSString *)action key:(NSString *)key toUser:(NSString *)toUser;
+ (instancetype)partWithAction:(NSString *)action key:(NSString *)key toUser:(NSString *)toUser;

+ (instancetype) messageWithKey:(NSString *)key toUser:(NSString *)toUser;
+ (instancetype) missedCallWithKey:(NSString *)key toUser:(NSString *)toUser;
+ (instancetype) activeCallWithKey:(NSString *)key toUser:(NSString *)toUser;

@end