//
// Created by Dusan Klinec on 01.11.15.
// Copyright (c) 2015 PhoneX. All rights reserved.
//

#import <Foundation/Foundation.h>
static NSString * PEX_PUSH_FIELD_ACK_ACTION = @"p";
static NSString * PEX_PUSH_FIELD_ACK_KEY = @"k";
static NSString * PEX_PUSH_FIELD_ACK_TIMESTAMP = @"t";

/**
 * Individual push message for acknowledgement. Part of PEXPushAckMsg sent to push server to let him know we received
 * and processed given push messages so it does not push them again.
 */
@interface PEXPushAckPart : NSObject <NSCoding, NSCopying>
@property(nonatomic) NSString * action;
@property(nonatomic) NSNumber * timestamp;

/**
* Identifier of the push message request.
* Generated by client.
* Used for duplicates avoidance.
* Client can identify this message in order to cancel its delivery to the target device, used in calls.
 *
 * Can be nil. If is not nil, push messages have to be ACKed individually
*/
@property(nonatomic) NSString * key;

-(NSMutableDictionary *) getSerializationBase;

- (id)initWithCoder:(NSCoder *)coder;
- (void)encodeWithCoder:(NSCoder *)coder;
- (id)copyWithZone:(NSZone *)zone;
- (NSString *)description;
- (BOOL)isEqual:(id)other;
- (BOOL)isEqualToPart:(PEXPushAckPart *)part;
- (NSUInteger)hash;
@end