//
// Created by Dusan Klinec on 28.11.14.
// Copyright (c) 2014 PhoneX. All rights reserved.
//

#import <Foundation/Foundation.h>

@class PEXPresenceState;

/**
* Presence update envelope for XMPP object.
* Raw presence data generated by presence center.
*/
@interface PEXPresenceUpdateEnvelope : NSObject <NSCoding, NSCopying>
@property(nonatomic) NSNumber * isAvailable;

/**
* Final message to be transmitted.
*/
@property(nonatomic) NSString * statusMessage;

/**
* State reference used to generate this envelope message.
*/
@property(nonatomic) PEXPresenceState * state;

- (instancetype)initWithIsAvailable:(NSNumber *)isAvailable statusMessage:(NSString *)statusMessage;
+ (instancetype)envelopeWithIsAvailable:(NSNumber *)isAvailable statusMessage:(NSString *)statusMessage;

- (NSString *)description;
- (id)initWithCoder:(NSCoder *)coder;
- (void)encodeWithCoder:(NSCoder *)coder;
- (id)copyWithZone:(NSZone *)zone;
@end