//
// Created by Dusan Klinec on 24.10.14.
// Copyright (c) 2014 PhoneX. All rights reserved.
//

#import <Foundation/Foundation.h>

//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dusanklinec/workspace/phonex2translate/SipUri.java
//

#ifndef _PEX_SIPURI_H_
#define _PEX_SIPURI_H_

@class PEXSIPURIParsedSipContact;
@class PEXSIPURIParsedSipUri;

/**
@brief Helper class for Sip uri manipulation in java space.
Allows to parse sip uris and check it.
*/
@interface PEXSipUri : NSObject {
}

+ (NSRegularExpression *) PEX_SIPURI_SIP_CONTACT_PATTERN;
+ (NSRegularExpression *) PEX_SIPURI_SIP_HOST_PATTERN;
+ (NSRegularExpression *) PEX_SIPURI_SIP_CONTACT_ADDRESS_PATTERN;
+ (NSRegularExpression *) PEX_SIPURI_SIP_CONTACT_EASY_PATTERN;
+ (NSRegularExpression *) PEX_SIPURI_SIP_URI_PATTERN;

- (instancetype)init;

/**
@brief Parse a sip contact
@param sipUri string sip contact
@return a ParsedSipContactInfos which contains uri parts. If not match return the object with blank fields
*/
+ (PEXSIPURIParsedSipContact *)parseSipContact:(NSString *)sipUri;

/**
@brief Return what should be display as caller id for this sip uri This is the merged and fancy way fallback to uri or user name if needed
@param uri the uri to display
@return the simple display
*/
+ (NSString *)getDisplayedSimpleContact:(NSString *)uri;

/**
@brief Transform sip uri into something that doesn't depend on remote display name For example, if you give "Display Name" <sip:user@@domain.com> It will return sip:user@@domain.com
@param sipContact full sip uri
@return simplified sip uri
*/
+ (NSString *)getCanonicalSipContact:(NSString *)sipContact;

/**
@brief Transform sip uri into something that doesn't depend on remote display name
@param sipContact full sip uri
@param includeScheme whether to include scheme in case of username
@return the canonical sip contact <br/> Example sip:user@@domain.com <br/> or user@@domain.com (if include scheme is false)
*/
+ (NSString *)getCanonicalSipContact:(NSString *)sipContact
                       includeScheme:(BOOL)includeScheme;

/**
@brief Removes SIP scheme from the username if there is some.
@param userName
@return
*/
+ (NSString *)stripSipScheme:(NSString *)userName;

/**
@brief Parse an uri
@param sipUri the uri to parse
@return parsed object
*/
+ (PEXSIPURIParsedSipUri *)parseSipUri:(NSString *)sipUri;

+ (NSString *)forgeSipUri:(NSString *)scheme
              withContact:(NSString *)contact;

+ (NSString *)encodeUser:(NSString *)user;

/**
@brief Extracts SIP from contact, returns null if the mockContacts if not properly formatted.
@param contact
@return
*/
+ (NSString *)getSipFromContact:(NSString *)contact;

/**
* Extracts domain from SIP address.
*/
+ (NSString *)getDomainFromSip:(NSString *)sip parsed: (PEXSIPURIParsedSipUri **) parsed;
@end

/**
@brief Holder for parsed sip contact information.
<br/> Basically wrap AoR. We should have something like " ParsedSipContactInfos#displayName < ParsedSipContactInfos#scheme : ParsedSipContactInfos#userName @@ ParsedSipContactInfos#domain >
*/
@interface PEXSIPURIParsedSipContact : NSObject {}
/**
@brief Contact display name.
*/
@property (nonatomic) NSString * displayName;
/**
@brief User name of AoR
*/
@property (nonatomic) NSString * userName;
/**
@brief Domaine name
*/
@property (nonatomic) NSString * domain;
/**
@brief Scheme of the protocol
*/
@property (nonatomic) NSString * scheme;

- (NSString *)description;

- (NSString *)toStringWithBoolean:(BOOL)includeDisplayName;

- (NSString *)getContactAddress;

- (instancetype)init;

- (void)copyAllFieldsTo:(PEXSIPURIParsedSipContact *)other;

@end

/**
@brief Holder for parsed sip uri information.
<br/> We should have something like " ParsedSipUriInfos#scheme : ParsedSipUriInfos#domain : ParsedSipUriInfos#port "
*/
@interface PEXSIPURIParsedSipUri : NSObject { }
/**
@brief Domain name/ip
*/
@property (nonatomic) NSString * domain;
/**
@brief Scheme of the protocol
*/
@property (nonatomic) NSString * scheme;
/**
@brief Port number
*/
@property (nonatomic) int port;

- (instancetype)init;

- (void)copyAllFieldsTo:(PEXSIPURIParsedSipUri *)other;

@end

#endif // _PEX_SIPURI_H_
