// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class PEXPbFileDetail;
@class PEXPbFileDetailBuilder;
@class PEXPbPresencePush;
@class PEXPbPresencePushBuilder;
@class PEXPbServerNotificationPush;
@class PEXPbServerNotificationPushBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, PEXPbPresencePushPEXPbStatus) {
  PEXPbPresencePushPEXPbStatusOnline = 0,
  PEXPbPresencePushPEXPbStatusOffline = 1,
  PEXPbPresencePushPEXPbStatusBusy = 2,
  PEXPbPresencePushPEXPbStatusAway = 3,
  PEXPbPresencePushPEXPbStatusDnd = 4,
  PEXPbPresencePushPEXPbStatusCustom = 5,
  PEXPbPresencePushPEXPbStatusOncall = 6,
  PEXPbPresencePushPEXPbStatusDevsleep = 7,
};

BOOL PEXPbPresencePushPEXPbStatusIsValidValue(PEXPbPresencePushPEXPbStatus value);


@interface PexpbPushRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PEXPbPresencePush : PBExtendableMessage {
@private
  BOOL hasCapabilitiesSkip_:1;
  BOOL hasSipRegistered_:1;
  BOOL hasServerGenerated_:1;
  BOOL hasCertNotBefore_:1;
  BOOL hasServerLastActivity_:1;
  BOOL hasCertHashShort_:1;
  BOOL hasCertHashFull_:1;
  BOOL hasStatusText_:1;
  BOOL hasCapabilitiesHash_:1;
  BOOL hasResourceId_:1;
  BOOL hasSipId_:1;
  BOOL hasAuxJson_:1;
  BOOL hasServerJsonAux_:1;
  BOOL hasVersion_:1;
  BOOL hasStatus_:1;
  BOOL capabilitiesSkip_:1;
  BOOL sipRegistered_:1;
  BOOL serverGenerated_:1;
  UInt64 certNotBefore;
  UInt64 serverLastActivity;
  NSString* certHashShort;
  NSString* certHashFull;
  NSString* statusText;
  NSString* capabilitiesHash;
  NSString* resourceId;
  NSString* sipId;
  NSString* auxJson;
  NSString* serverJsonAux;
  UInt32 version;
  PEXPbPresencePushPEXPbStatus status;
  NSMutableArray * capabilitiesArray;
}
- (BOOL) hasVersion;
- (BOOL) hasCertHashShort;
- (BOOL) hasCertHashFull;
- (BOOL) hasCertNotBefore;
- (BOOL) hasStatus;
- (BOOL) hasStatusText;
- (BOOL) hasCapabilitiesSkip;
- (BOOL) hasCapabilitiesHash;
- (BOOL) hasSipRegistered;
- (BOOL) hasResourceId;
- (BOOL) hasSipId;
- (BOOL) hasAuxJson;
- (BOOL) hasServerGenerated;
- (BOOL) hasServerLastActivity;
- (BOOL) hasServerJsonAux;
@property (readonly) UInt32 version;
@property (readonly, strong) NSString* certHashShort;
@property (readonly, strong) NSString* certHashFull;
@property (readonly) UInt64 certNotBefore;
@property (readonly) PEXPbPresencePushPEXPbStatus status;
@property (readonly, strong) NSString* statusText;
@property (readonly, strong) PBArray * capabilities;
- (BOOL) capabilitiesSkip;
@property (readonly, strong) NSString* capabilitiesHash;
- (BOOL) sipRegistered;
@property (readonly, strong) NSString* resourceId;
@property (readonly, strong) NSString* sipId;
@property (readonly, strong) NSString* auxJson;
- (BOOL) serverGenerated;
@property (readonly) UInt64 serverLastActivity;
@property (readonly, strong) NSString* serverJsonAux;
- (NSString*)capabilitiesAtIndex:(NSUInteger)index;

+ (PEXPbPresencePush*) defaultInstance;
- (PEXPbPresencePush*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PEXPbPresencePushBuilder*) builder;
+ (PEXPbPresencePushBuilder*) builder;
+ (PEXPbPresencePushBuilder*) builderWithPrototype:(PEXPbPresencePush*) prototype;
- (PEXPbPresencePushBuilder*) toBuilder;

+ (PEXPbPresencePush*) parseFromData:(NSData*) data;
+ (PEXPbPresencePush*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PEXPbPresencePush*) parseFromInputStream:(NSInputStream*) input;
+ (PEXPbPresencePush*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PEXPbPresencePush*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PEXPbPresencePush*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PEXPbPresencePushBuilder : PBExtendableMessageBuilder {
@private
  PEXPbPresencePush* result;
}

- (PEXPbPresencePush*) defaultInstance;

- (PEXPbPresencePushBuilder*) clear;
- (PEXPbPresencePushBuilder*) clone;

- (PEXPbPresencePush*) build;
- (PEXPbPresencePush*) buildPartial;

- (PEXPbPresencePushBuilder*) mergeFrom:(PEXPbPresencePush*) other;
- (PEXPbPresencePushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PEXPbPresencePushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (UInt32) version;
- (PEXPbPresencePushBuilder*) setVersion:(UInt32) value;
- (PEXPbPresencePushBuilder*) clearVersion;

- (BOOL) hasCertHashShort;
- (NSString*) certHashShort;
- (PEXPbPresencePushBuilder*) setCertHashShort:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearCertHashShort;

- (BOOL) hasCertHashFull;
- (NSString*) certHashFull;
- (PEXPbPresencePushBuilder*) setCertHashFull:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearCertHashFull;

- (BOOL) hasCertNotBefore;
- (UInt64) certNotBefore;
- (PEXPbPresencePushBuilder*) setCertNotBefore:(UInt64) value;
- (PEXPbPresencePushBuilder*) clearCertNotBefore;

- (BOOL) hasStatus;
- (PEXPbPresencePushPEXPbStatus) status;
- (PEXPbPresencePushBuilder*) setStatus:(PEXPbPresencePushPEXPbStatus) value;
- (PEXPbPresencePushBuilder*) clearStatus;

- (BOOL) hasStatusText;
- (NSString*) statusText;
- (PEXPbPresencePushBuilder*) setStatusText:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearStatusText;

- (NSMutableArray *)capabilities;
- (NSString*)capabilitiesAtIndex:(NSUInteger)index;
- (PEXPbPresencePushBuilder *)addCapabilities:(NSString*)value;
- (PEXPbPresencePushBuilder *)setCapabilitiesArray:(NSArray *)array;
- (PEXPbPresencePushBuilder *)clearCapabilities;

- (BOOL) hasCapabilitiesSkip;
- (BOOL) capabilitiesSkip;
- (PEXPbPresencePushBuilder*) setCapabilitiesSkip:(BOOL) value;
- (PEXPbPresencePushBuilder*) clearCapabilitiesSkip;

- (BOOL) hasCapabilitiesHash;
- (NSString*) capabilitiesHash;
- (PEXPbPresencePushBuilder*) setCapabilitiesHash:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearCapabilitiesHash;

- (BOOL) hasSipRegistered;
- (BOOL) sipRegistered;
- (PEXPbPresencePushBuilder*) setSipRegistered:(BOOL) value;
- (PEXPbPresencePushBuilder*) clearSipRegistered;

- (BOOL) hasResourceId;
- (NSString*) resourceId;
- (PEXPbPresencePushBuilder*) setResourceId:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearResourceId;

- (BOOL) hasSipId;
- (NSString*) sipId;
- (PEXPbPresencePushBuilder*) setSipId:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearSipId;

- (BOOL) hasAuxJson;
- (NSString*) auxJson;
- (PEXPbPresencePushBuilder*) setAuxJson:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearAuxJson;

- (BOOL) hasServerGenerated;
- (BOOL) serverGenerated;
- (PEXPbPresencePushBuilder*) setServerGenerated:(BOOL) value;
- (PEXPbPresencePushBuilder*) clearServerGenerated;

- (BOOL) hasServerLastActivity;
- (UInt64) serverLastActivity;
- (PEXPbPresencePushBuilder*) setServerLastActivity:(UInt64) value;
- (PEXPbPresencePushBuilder*) clearServerLastActivity;

- (BOOL) hasServerJsonAux;
- (NSString*) serverJsonAux;
- (PEXPbPresencePushBuilder*) setServerJsonAux:(NSString*) value;
- (PEXPbPresencePushBuilder*) clearServerJsonAux;
@end

@interface PEXPbFileDetail : PBGeneratedMessage {
@private
  BOOL hasUploadedTime_:1;
  BOOL hasNonce2_:1;
  BOOL hasFromUser_:1;
  BOOL hasVersion_:1;
  UInt64 uploadedTime;
  NSString* nonce2;
  NSString* fromUser;
  UInt32 version;
}
- (BOOL) hasVersion;
- (BOOL) hasNonce2;
- (BOOL) hasFromUser;
- (BOOL) hasUploadedTime;
@property (readonly) UInt32 version;
@property (readonly, strong) NSString* nonce2;
@property (readonly, strong) NSString* fromUser;
@property (readonly) UInt64 uploadedTime;

+ (PEXPbFileDetail*) defaultInstance;
- (PEXPbFileDetail*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PEXPbFileDetailBuilder*) builder;
+ (PEXPbFileDetailBuilder*) builder;
+ (PEXPbFileDetailBuilder*) builderWithPrototype:(PEXPbFileDetail*) prototype;
- (PEXPbFileDetailBuilder*) toBuilder;

+ (PEXPbFileDetail*) parseFromData:(NSData*) data;
+ (PEXPbFileDetail*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PEXPbFileDetail*) parseFromInputStream:(NSInputStream*) input;
+ (PEXPbFileDetail*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PEXPbFileDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PEXPbFileDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PEXPbFileDetailBuilder : PBGeneratedMessageBuilder {
@private
  PEXPbFileDetail* result;
}

- (PEXPbFileDetail*) defaultInstance;

- (PEXPbFileDetailBuilder*) clear;
- (PEXPbFileDetailBuilder*) clone;

- (PEXPbFileDetail*) build;
- (PEXPbFileDetail*) buildPartial;

- (PEXPbFileDetailBuilder*) mergeFrom:(PEXPbFileDetail*) other;
- (PEXPbFileDetailBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PEXPbFileDetailBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (UInt32) version;
- (PEXPbFileDetailBuilder*) setVersion:(UInt32) value;
- (PEXPbFileDetailBuilder*) clearVersion;

- (BOOL) hasNonce2;
- (NSString*) nonce2;
- (PEXPbFileDetailBuilder*) setNonce2:(NSString*) value;
- (PEXPbFileDetailBuilder*) clearNonce2;

- (BOOL) hasFromUser;
- (NSString*) fromUser;
- (PEXPbFileDetailBuilder*) setFromUser:(NSString*) value;
- (PEXPbFileDetailBuilder*) clearFromUser;

- (BOOL) hasUploadedTime;
- (UInt64) uploadedTime;
- (PEXPbFileDetailBuilder*) setUploadedTime:(UInt64) value;
- (PEXPbFileDetailBuilder*) clearUploadedTime;
@end

@interface PEXPbServerNotificationPush : PBExtendableMessage {
@private
  BOOL hasVersion_:1;
  UInt32 version;
  NSMutableArray * filesArray;
}
- (BOOL) hasVersion;
@property (readonly) UInt32 version;
@property (readonly, strong) NSArray * files;
- (PEXPbFileDetail*)filesAtIndex:(NSUInteger)index;

+ (PEXPbServerNotificationPush*) defaultInstance;
- (PEXPbServerNotificationPush*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PEXPbServerNotificationPushBuilder*) builder;
+ (PEXPbServerNotificationPushBuilder*) builder;
+ (PEXPbServerNotificationPushBuilder*) builderWithPrototype:(PEXPbServerNotificationPush*) prototype;
- (PEXPbServerNotificationPushBuilder*) toBuilder;

+ (PEXPbServerNotificationPush*) parseFromData:(NSData*) data;
+ (PEXPbServerNotificationPush*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PEXPbServerNotificationPush*) parseFromInputStream:(NSInputStream*) input;
+ (PEXPbServerNotificationPush*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PEXPbServerNotificationPush*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PEXPbServerNotificationPush*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PEXPbServerNotificationPushBuilder : PBExtendableMessageBuilder {
@private
  PEXPbServerNotificationPush* result;
}

- (PEXPbServerNotificationPush*) defaultInstance;

- (PEXPbServerNotificationPushBuilder*) clear;
- (PEXPbServerNotificationPushBuilder*) clone;

- (PEXPbServerNotificationPush*) build;
- (PEXPbServerNotificationPush*) buildPartial;

- (PEXPbServerNotificationPushBuilder*) mergeFrom:(PEXPbServerNotificationPush*) other;
- (PEXPbServerNotificationPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PEXPbServerNotificationPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (UInt32) version;
- (PEXPbServerNotificationPushBuilder*) setVersion:(UInt32) value;
- (PEXPbServerNotificationPushBuilder*) clearVersion;

- (NSMutableArray *)files;
- (PEXPbFileDetail*)filesAtIndex:(NSUInteger)index;
- (PEXPbServerNotificationPushBuilder *)addFiles:(PEXPbFileDetail*)value;
- (PEXPbServerNotificationPushBuilder *)setFilesArray:(NSArray *)array;
- (PEXPbServerNotificationPushBuilder *)clearFiles;
@end


// @@protoc_insertion_point(global_scope)
